# Generated by Django 4.1 on 2022-09-03 19:46

import api.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curve',
            name='reach',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=10, validators=[api.validators.reach_validator]),
        ),
    ]
